version: '3'

services:

    db:
        image: postgres
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=mehdi
          - POSTGRES_PASSWORD=password
        ports:
          - "5432:5432"

    redis:
        image: redis:latest
        ports:
          - "6379:6379"


    # telegramVipBot:
    #     image: app
    #     command: python manage.py runvipbot
          
    #     depends_on: 
    #       - db
    #       - web
    #       - redis

    #     links: 
    #       - redis

    #     volumes:
    #       - .:/usr/src/app

    #     environment:
    #       - DB_HOST=db
    #       - DB_NAME=postgres
    #       - DB_USER=mehdi
    #       - DB_PASS=password
      


    telegramSiteBot:
      image: app
      command: python manage.py runsitebot
        
      depends_on: 
        - db
        - web
        - redis

      links: 
        - redis

      volumes:
        - .:/usr/src/app

      environment:
        - DB_HOST=db
        - DB_NAME=postgres
        - DB_USER=mehdi
        - DB_PASS=password

            
    web:
        image: app
        command: > 
          bash -c "python manage.py makemigrations && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 bot.asgi:application"
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        environment:
          - DB_HOST=db
          - DB_NAME=postgres
          - DB_USER=mehdi
          - DB_PASS=password
          - REDIS_HOST=redis
        depends_on:
          - db
          - redis
        links: 
          - redis

    celery:
        restart: always
        image: app
        command: celery -A bot worker --loglevel=debug --concurrency=8
        depends_on:
          - db
          - redis
          - web
        volumes:
          - .:/usr/src/app
        environment:
          - DB_HOST=db
          - DB_NAME=postgres
          - DB_USER=mehdi
          - DB_PASS=password


    celery-beat:
      restart: always
      image: app
      command: celery -A bot beat -l info
      depends_on:
        - db
        - redis
        - web
      volumes:
        - .:/usr/src/app

      environment:
        - DB_HOST=db
        - DB_NAME=postgres
        - DB_USER=mehdi
        - DB_PASS=password