version: '3'

services:

    
    telegrambot:
        image: telegrambot
        
        volumes:
            - ./db.sqlite3:/usr/src/app/db.sqlite3
    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
