# Generated by Django 3.2 on 2021-04-30 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBotMember',
            fields=[
                ('customer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
    ]
