# Generated by Django 3.2 on 2021-05-10 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBotMember',
            fields=[
                ('customer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='ProductPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=500)),
                ('plan', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.sitebotmember')),
            ],
        ),
    ]
