# Generated by Django 3.2 on 2021-04-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('unknown', 'ناشناخته')], max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('instagram', 'ارتباط از اینستا'), ('subscribed', 'عضو کانال'), ('unsubscribed', 'لغو عضویت'), ('guest', 'مهمان'), ('conditions', 'درخواست شرایط'), ('resubscribed', 'تمدید عضویت'), ('unresubscribed', 'عدم تمدید')], max_length=20, null=True)),
                ('conract_start_date', models.DateTimeField(blank=True, null=True)),
                ('contract_end_date', models.DateTimeField(blank=True, null=True)),
                ('skill_level', models.CharField(blank=True, choices=[('advanced', 'پیشرفته'), ('intermediate', 'متوسط'), ('beginner', 'مبتدی')], max_length=20, null=True)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
