# Generated by Django 3.2 on 2021-04-27 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210427_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipmembers',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('unknown', 'ناشناخته'), ('female', 'زن')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vipmembers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
