# Generated by Django 3.2 on 2021-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210427_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipmembers',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
