# Generated by Django 3.2 on 2021-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_vipmembers_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipmembers',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vipmembers',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('unknown', 'ناشناخته')], max_length=10, null=True),
        ),
    ]
