# Generated by Django 3.2 on 2021-04-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_vipmembers_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBotMember',
            fields=[
                ('customer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vipmembers',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زن'), ('male', 'مرد'), ('unknown', 'ناشناخته')], max_length=10, null=True),
        ),
    ]
