# Generated by Django 3.2 on 2021-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_auto_20210429_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipmembers',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('unknown', 'ناشناخته')], max_length=10, null=True),
        ),
    ]
